### PR TITLE
(MODULES-8197) Allow UNC path to be specified for iis_site:physicalpath

### PR DESCRIPTION
**Pull request by palintir**

### CODE REVIEW

**Comment by RandomNoun7** [comment]
Hello Adrian,
Thank you for this Pull Request. If you'll notice, [the unit tests are failing](https://ci.appveyor.com/project/puppetlabs/puppetlabs-iis-9rnb2/builds/19975444/job/mm5eb1h5c6r3gl6a). This is because your new regex pattern was added to the logpath parameter, but the new unit test was added to the physicalpath parameter. If you intend both then please add a unit test to the logpath parameter and also add the regex pattern to the physicalpath parameter in the type file.

Also, please review the contributing.md file regarding best practices advice for branch naming (item 2 of [More About Commits](https://github.com/puppetlabs/puppetlabs-iis/blob/master/CONTRIBUTING.md#more-about-commits)), and [commit messages](https://github.com/puppetlabs/puppetlabs-iis/blob/master/CONTRIBUTING.md#the-commit-message). Specifically please move these commits to a feature branch rather than master (a branch name along the lines of `MODULES-8197-allow-unc-paths` would be an example), and please provide a more descriptive commit message that describes things like the reason for the change and a short description of the implementation.

There is no rush, as IIS is not prioritized for work for us on the Windows team at the moment, and before we can merge this change into master, one of us will need to go in and add commits to your PR that will add acceptance testing for these changes. We can't guarantee when IIS will come up in our priority list again, but if your changes are ready to go before we get there it will make it easier and faster to get your changes merged.

Thanks again for efforts at improving this module and I hope to get this merged in for you as quickly as we can work together to do so.

Thanks,
Bill

**Comment by lionce** [comment]
Hello @palintir ,

Thank you for your PR. As you can see [the unit tests are failing](https://ci.appveyor.com/project/puppetlabs/puppetlabs-iis-9rnb2/builds/19975444/job/mm5eb1h5c6r3gl6a). In order to merge this PR, please update the pull request accordingly.

**Comment by sheenaajay** [comment]
Hi @palintir .Could you please resolve the conflicts and rebase with the latest master too. Thank you.

**Comment by david22swan** [comment]
@palintir Apologies, but due to the amount of time this PR has been left to lie fallow and your lack of response when pinged on it, we feel that we should now close it. We are sorry if this is an inconvenience to you in any way and of course would be happy to review/merge any future contributions that you choose to make.
Best Wishes

**Pull request closed without merging**
