### PR TITLE
(MODULES-6020) Fix iis_application setting applicationpool

### PR DESCRIPTION
**Pull request by nickadcock-bango**
This PR fixes the iis_application type by adding the code to update the applicationpool if it has changed.

https://tickets.puppetlabs.com/browse/MODULES-6020

### CODE REVIEW

**Comment by jpogran** [comment]
Thanks @nickadcock-bango for the PR which fixes MODULES-6020. Can you update the commit message with something more descriptive?

I know we don't have any tests here that cover changing any of these parameters here https://github.com/puppetlabs/puppetlabs-iis/blob/master/spec/acceptance/iis_application_spec.rb, can you add one for applicationpool and I'll ticket adding others.

**Comment by nickadcock-bango** [comment]
Sure thing. Any suggestions on what kind of information the commit message should contain?

**Comment by jpogran** [comment]
If you take the edit i did to the PR description that would be fine

**Comment by nickadcock-bango** [comment]
Thank you. I have never actually edited the commit message of an existing commit. Could you give me a hint on how? Thanks

**Comment by michaeltlombardi** [comment]
@nickadcock-bango: You can alter your last commit by using the command `git commit --amend`.

Github actually has a pretty good doc on the topic: https://help.github.com/articles/changing-a-commit-message/

**Comment by jpogran** [comment]
I've rebased, updated the commit message, and added an acceptance test

**Review by michaeltlombardi — APPROVED** [review]
🥇

**Comment by nickadcock-bango** [comment]
Thanks guys. Apologies for being unresponsive lately, I've been out of the country for a bit. I'll review what you've done so I know what to do the next time

**Pull request merged**
