### PR TITLE
MODULES-9492. Patching 'exist ?' method before trying to create VD

### PR DESCRIPTION
**Pull request by lmayala**
Existence of virtual directory was not being checked before the attempt to create it so it was failing after first run.

### CODE REVIEW

**Comment by RandomNoun7** [comment]
@lmayala Thanks for this Pull Request. I'm investigating right now why it is that the existing tests aren't catching this bug. Can you do me a favor though? The name of this pull request and the commit message for the commit both seem to contain an unprintable character. Could you please remove it to avoid any errors in the way git or github displays your pull request and your commit?

**Comment by RandomNoun7** [comment]
The real bug here appears to be a naming mismatch error due to differences in the type of slash character used by the user, and the direction expected by the module. See the [latest ticket comment](https://tickets.puppetlabs.com/browse/MODULES-9492?focusedCommentId=669173&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-669173) for details.

**Comment by lmayala** [comment]
Thanks Bill. I answered in the ticket. Let me know if I should go on on this PR or if it is better to create a new one.

**Comment by lionce** [comment]
Hello @lmayala ,

As Bill responded in the ticket, please do continue your work on the existing PR as you have time available. Since there is a workaround available it's ok for us to wait for a while for you to finish this code. If you need any help, please let us know. 

Cheers!

**Comment by michaeltlombardi** [comment]
Since this hasn't seen any activity in about six months, I'm going to go ahead and close this pull request for the time being. Please re-open this pull request once the next actions are addressed, new information is available, or you have a question related to this pull request. We've become aware of difficulties re-opening pull requests, in the event you cannot please mention `puppetlabs/modules`  with an @ sign in front and we'll re-open this pull request.

Closing the pull request doesn't mean we don't consider this change valuable, just that there are things that need to be addressed before it can be merged. If you have any questions or concerns, please don't hesitate to ping us in slack.puppet.com.

**Pull request closed without merging**
